### ISSUE TITLE
cloud function

### ISSUE THREAD

**Issue by wallstudios** [fgilio/pdftk-gcf#1]
Trying to get a pdf filler working in google cloud and saw this. Does it still work?

**Comment by fgilio** [comment]
I'm not currently using it, but I don't see why it wouldn't work. I tested it with the Node 8 environment when it was in beta.

EDIT: Just saw your comment is from 4 days ago, did you try it?

**Comment by Wian-TMC** [comment]
The NPM package is not available anymore?

**Comment by fgilio** [comment]
> The NPM package is not available anymore?

Hi @Wian-TMC! I think I never published the package in npm, just used it from git.
I'm going to mark this as deprecated, as I no longer use it and I have no idea if it still works with GCF new runtimes.
