### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by avaco** [fgilio/pdftk-gcf#2]
hi, so thanks for the library first, quite helpful.  Just to mention you have a typo in your Read.me

it says to install: npm i pdftk-gcp  
it should be: npm i pdftk-gcf

same thing for the require
require('pdftk-gcp')
should be: require('pdftk-gcf')

Cheers,

**Comment by fgilio** [comment]
Lol thanks for the notice and I'm glad you found it useful!
